---
all:
  vars:
    install_rke2_version: v1.30.8+rke2r1
rke2_cluster:
  children:
    rke2_servers:
      vars:
        rke2_config:
          node-label:
            - serverGroupLabel=true
      hosts:
        k01-m.lan:
          node_labels:
            - server0Label=true
          node_ip: 10.10.1.30
          node_name: k01-m.lan
          bind_address: 10.10.1.30
          advertise_address: 10.10.1.30
          node_taints:
            - CriticalAddonsOnly=true:NoSchedule
        k02-m.lan:
          node_labels:
            - server0Label=true
          node_ip: 10.10.1.31
          node_name: k02-m.lan
        k03-m.lan:
          node_labels:
            - server0Label=true
          node_ip: 10.10.1.32
          node_name: k03-m.lan
    rke2_agents:
      vars:
        rke2_config:
          node-label:
            - agentGroupLabel=true
      hosts:
        k04-n.lan:
          node_labels:
            - agent0Label=true
          node_ip: 10.10.1.33
          node_name: k04-n.lan
        k05-n.lan:
          node_labels:
            - agent0Label=true
          node_ip: 10.10.1.34
          node_name: k05-n.lan
        k06-n.lan:
          node_labels:
            - agent0Label=true
          node_ip: 10.10.1.35
          node_name: k06-n.lan
